# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Provided by the web container, so aligned with Jetty
      - dependency-name: "javax.servlet:javax.servlet-api"
      # Newer versions require code changes
      - dependency-name: "org.jboss.resteasy:resteasy-client"
        versions: [">=4.0.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
