sudo: required

language: java

services:
  - docker

env:
  global:
    - DOCKER_CACHE_DIR=$HOME/.docker-images

matrix:
  fast_finish: true

before_install:
  - chmod +x travis/*.sh
  - travis/before_install.sh

script: ./travis/test.sh

jobs:
  include:
  - stage: integration-test
    script: ./travis/integration-test.sh
    env:
      - GITLAB_VERSION=8.17.4
  - stage: integration-test
    script: ./travis/integration-test.sh
    env:
      - GITLAB_VERSION=9.5.5
  - stage: integration-test
    script: ./travis/integration-test.sh
    env:
      - GITLAB_VERSION=latest


cache:
  directories:
  - $DOCKER_CACHE_DIR
  - $HOME/.m2/repository
  - $HOME/.m2/wrapper
before_cache:
  - travis/before_cache.sh
