version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:14.7.0-ce.0'
    restart: "no"
    hostname: 'localhost'
    ports:
      - '10080:80'
      - '10022:22'
    volumes:
      - '/srv/docker/gitlab/config:/etc/gitlab'
      - '/srv/docker/gitlab/logs:/var/log/gitlab'
      - '/srv/docker/gitlab/data:/var/opt/gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        gitlab_rails['initial_root_password'] = 'password'

  jenkins:
    restart: "no"
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /srv/docker/jenkins:/var/jenkins_home
